trigger:
- main

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'

    - script: npm install
      displayName: 'Install dependencies'

    - script: npm run build
      displayName: 'Run React Build with CI=false'
      env:
        CI: 'false'

    - script: |
        echo "Build directory contents:"
        ls -la build
      displayName: 'Debug: List build directory'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'build'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  jobs:
  - job: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'

    - script: |
        echo "DEBUG: Contents of drop folder after artifact download:"
        ls -la $(System.ArtifactsDirectory)/drop
      displayName: 'Debug: List drop folder after download'

    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure for Students (cad91fef-fc90-457e-89b1-7221750f7c9e)'
        appType: 'webAppLinux'
        WebAppName: 'CIpractice'
        packageForLinux: '$(System.ArtifactsDirectory)/drop'
        RuntimeStack: 'NODE|22-lts'
