- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Npm@1
      inputs:
        command: 'install'

    - script: |
        npm run build
      displayName: 'Run React Build with CI=false'
      env:
        CI: 'false'

    - script: |
        echo "Build directory contents:"
        ls -la build
      displayName: 'Debug: List build directory'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'build'
        ArtifactName: 'drop'
        publishLocation: 'Container'
